_BASE_: "./faster_rcnn_R_50_FPN_3x.yaml"
SOLVER:
  MAX_ITER: 1000
  IMS_PER_BATCH: 2
  PERIODIC_CHECKPOINTER:
    ENABLED: False
    PERIOD: 50
  BEST_CHECKPOINTER:
    ENABLED: True
    # METRIC: "total_loss"
    # MODE: "min"
    METRIC: "bbox/AP50"
    MODE: "max"
DATASETS:
    TRAIN: ('coco_train',)
    TEST: ('coco_val',)
TEST:
  EVAL_PERIOD: 100